language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
- make github
env:
  global:
    secure: WGqU3IU/gu3+u3A7rxALda2MKIhNpd2W44pPYptxnZxCd1AOdTRaYDe+13OsBRaCn43wRPUVHs4bglAOcC1TQBFL+eIgY9WKoK07c7viIkrMhkv/nu0WJagFG+PEj/Wv2nQC4rtzMg2QC2DqKOavxexn5LJqPidyZcWQ4KEaLeg=
