language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
- make github
env:
  global:
    secure: "Z2PwTH35xay8gGkvKamcF/Gv7g83aJqysu7Zoo0cD+5mXXhZRFulnzZzd/ufLxfY7boUyhJbifmu31OQZ7O4d2PnA9AOg8/RAL3a12uy3Gy+LrKEGKcucqP4gr8XVcYguWbZxI1neE/a4QGns7kLnvHEelEMQXfM5d6Cyw0mXT8="
#after_success: bash deploy.sh
