language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish
- make github
env:
  global:
    secure: N3EqdHAlzBdqbdlrGZSDoPkp8dv41bJn0mszWMkH48CakBlLioKjmWYwqkaKZl+5ZxDXubGq7sBNDZA+kLaAQb0MMEUU+vAj/wmvZr0qzSICRnabQdu1EH8OOFFolRzejRbvGrVCEmoBrRyINMsx5ye3tv88Z2cuiPKovxFHcoY=
